Change re-upload behaviour of storage requests
biigle/user-storage pull request #28
Opened 2024-04-09 08:37 UTC by lehecht

Increased the number of retries to 3 and added an 5s delay before re-uploading files.

2024-04-09 10:25 UTC, mzur requested changes
This doesn't resolve #11 yet, as the issue is also about the "skip failed files and ask at the end" strategy.

2024-04-09 10:25 UTC, mzur commented on src/resources/assets/js/createContainer.vue
>                      }
This doesn't work correctly, yet. The method must return a promise. If you introduce a delay via timeout, you have to build a promise for that yourself. It can work like this:
```js
return new Vue.Promise((resolve) => {
   setTimeout(() => resolve(this.uploadBlob(blob, prefix, chunkIndex, totalChunks, retryCount + 1)), 5000);
});

2024-04-10 05:31 UTC, lehecht commented
> This doesn't resolve #11 yet, as the issue is also about the "skip failed files and ask at the end" strategy.

Ah, thanks! I didn't know this keyword also works. I looked up for these, but only got something like 'resolves', 'fixes', 'closes'.

2024-04-10 05:37 UTC, lehecht commented on src/resources/assets/js/createContainer.vue
>                      }
Thanks! I didn't know that. When I tested the code, everything seems to work. But perhaps I didn't test far enough to see the problems. Could you maybe explain, what problems/errors are being caused without the promise?

2024-04-10 07:15 UTC, mzur commented on src/resources/assets/js/createContainer.vue
>                      }
When you had no problems with the upload, the error handling code here was never called :wink: 

The `uploadBlob()` method is called [here](https://github.com/biigle/user-storage/blob/7fe75357208c5f1dc922000ecd2e5fc0b73cfadc/src/resources/assets/js/createContainer.vue#L338) and [here](https://github.com/biigle/user-storage/blob/7fe75357208c5f1dc922000ecd2e5fc0b73cfadc/src/resources/assets/js/createContainer.vue#L365). In both cases a returned promise is expected so the calling method can do something when the blob finished uploading. If no promise were returned, an error would be thrown.

2024-04-10 07:17 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> +
```suggestion

```

2024-04-10 07:19 UTC, mzur approved these changes

2024-04-10 07:19 UTC, merged