Add skip and retry option for failed file uploads
biigle/user-storage pull request #30
Opened 2024-05-13 11:20 UTC by lehecht

- [ ] Add button and functionality to retry upload
- [ ] Add button and functionality to skip failed files
- [ ] Prevent outdated delete requests to be executed
- [ ] Handle duplicated files
- [ ] Handle exceeded storage quota
- [ ] Create PR for dev-modules to update fileBrowser
- [ ] Fix editable fileBrowser after successfull upload
- [ ] Fix 404 error for delete requests

2024-05-22 05:45 UTC, lehecht commented on src/Http/Requests/StoreStorageRequestFile.php
> +            'retry' => $this->toBoolean($this->input('retry')),
If I don't use this, it cannot validate js-booleans. How do you validate them otherwise? Or do you use 0 or 1 in the vue components, because these can be validated?

2024-05-22 05:53 UTC, lehecht commented on src/Http/Requests/StoreStorageRequestFile.php
> +                ->where('storage_request_files.path','LIKE', '%'.$filename.'%')
Can you explain, in what case an error should be thrown?
I read your comment [there](https://github.com/biigle/user-storage/blob/15a9d3133371313d49179edd4fb1a021ae09b526/src/Http/Requests/StoreStorageRequestFile.php#L177-L183) and thought there shouldn't be two copies in different directories.

2024-05-22 07:01 UTC, mzur commented on src/Http/Requests/StoreStorageRequestFile.php
> +                ->where('storage_request_files.path','LIKE', '%'.$filename.'%')
The error should be thrown if a file `abcd/file.jpg` is uploaded in one request and then `abcd/file.jpg` should be uploaded again in another request. This is done to prevent issues when the file is deleted because it exists only once in the storage backend (but the upload would add the file size twice to the used storage quota). If a new file `dcba/file.jpg` is uploaded there is no issue and there should be no error. Basically you can revert the change here (except the error message key that you need).

2024-05-22 07:02 UTC, mzur commented on src/Http/Requests/StoreStorageRequestFile.php
> +                ->where('storage_request_files.path','LIKE', '%'.$filename.'%')
Also, feel free to extend the comment so future readers understand it better.

2024-05-22 07:07 UTC, mzur commented on src/Http/Requests/StoreStorageRequestFile.php
> +            'retry' => $this->toBoolean($this->input('retry')),
There are no issues with booleans when the request is sent as JSON. In your case you upload the file as `FormData` so this is likely the cause. In a normal form, booleans are also sent as `0` or `1` so I suggest you do this here, too, instead of implementing special logic in the backend.

2024-05-22 07:17 UTC, lehecht commented
@mzur 
I just noticed that `$success` never becomes `true` [here](https://github.com/biigle/user-storage/blob/15a9d3133371313d49179edd4fb1a021ae09b526/src/Http/Controllers/Api/StorageRequestFileController.php#L119). The only bool that can be returned is `false`.
So even when the upload was successfull it does not stop the loop. Should I change that?

2024-05-22 07:29 UTC, mzur commented
Yes, good catch! I think `$success !== false` should do the trick.

2024-05-22 08:32 UTC, lehecht commented
@mzur 
> Somehow I produced an inconsistent state when I combined duplicate files with failed files. I uploaded files A and B first. Then I created a new storage request with files A, B and C. File A intentionally failed, file B was detected as duplicate and file C succeeded. However, now both panels (files failed and duplicate files) are shown and I can click on "retry" but nothing happens. A second run (without failure) worked fine.

Did you upload file A and B in one directory of one request? If yes, how did you make file A fail? I'm a bit confused, because file A should also be recognized as duplicate, like B. Or did I get you wrong?

2024-05-22 08:58 UTC, mzur commented
> If yes, how did you make file A fail? I'm a bit confused, because file A should also be recognized as duplicate, like B.

I added a random `throw new Exception()` in the `StoreStorageRequestFile::rules()` method, so the failure occurred before the duplicate check.

2024-05-23 09:20 UTC, lehecht commented on tests/Http/Controllers/Api/StorageRequestFileControllerTest.php
This was because of the `fresh()` method, that creates a whole new object. I replaced it by `refresh()` which should not change the http status of already created objects.

2024-05-23 12:45 UTC, mzur requested changes
New high-level comments:

- If there is a validation error (code 422) other than the "duplicate file", it should be shown with `handleErrorResponse`. Currently it will be shown just like any failed file upload (e.g. code 500) and the user will try again without any chance for success.

- When there is a failed file and I click on "Ignore", there is a quick flash of the "Add Directory", "Submit" etc. buttons. Maybe the loading state is not enabled for the final submission of the storage request in this case?

- If all file uploads failed, the "Ignore" button is a bit misleading, since the whole storage request won't be created in this case. We should update the text as follows: "All file uploads failed. You can cancel the storage request or retry the upload." Then the "Ignore" button should say "Cancel".

2024-05-23 12:45 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> -        },
This can be restored. The new `loading` watcher does the same but worse.

2024-05-23 12:45 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> -        },
I don't see a reason why the computed properties should be changed to methods. You can update the computed properties in the same way.

2024-05-23 12:45 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> +                    this.finishIncomplete = this.failedFiles.length > 0;
This could be a computed property, too.

2024-05-23 12:55 UTC, mzur commented
The compiled `src/public/` files are also still missing.

2024-05-24 05:40 UTC, lehecht commented on tests/Http/Controllers/Api/StorageRequestFileControllerTest.php
> -
This would fail now, because I needed to move the model deletion into the deleteJob.

2024-05-24 07:34 UTC, lehecht commented on tests/Http/Controllers/Api/StorageRequestFileControllerTest.php
> +        $this->assertEquals(3, $f->retry_count);
I set retry on true for all chunks currently, but I can change that if you want.

2024-05-24 07:57 UTC, lehecht commented on src/Http/Controllers/Api/StorageRequestFileController.php
> +
Did I understand you correctly that when a storage request file was already saved, only the size is updated and the file model is returned?

2024-05-24 07:59 UTC, mzur commented on tests/Http/Controllers/Api/StorageRequestFileControllerTest.php
> -
Ok!

2024-05-24 08:00 UTC, mzur commented on tests/Http/Controllers/Api/StorageRequestFileControllerTest.php
> +        $this->assertEquals(3, $f->retry_count);
IMO it should be true only if an upload failed and is uploaded again.

2024-05-24 08:04 UTC, mzur commented on src/Http/Controllers/Api/StorageRequestFileController.php
> +
Currently, if a (non-chunked) file is uploaded again, the size is updated *and the file is uploaded to the storage disk again*. But since we skip existing chunks now, I think we should also skip existing non-chunked files (and don't update the size or upload it to the storage disk).

2024-05-27 10:03 UTC, lehecht commented on src/Http/Controllers/Api/StorageRequestFileController.php
> +                $fileModel = $fileModel->refresh();
Because otherwise the `retry_count` is not initialized and would start at zero. Thats why I needed `refresh()` to update the object and set `retry_count` it to one.

2024-05-27 11:49 UTC, lehecht commented on src/resources/assets/js/createContainer.vue
> +                }
I added this because I ran into an undefined request when the whole storage request should be deleted. The the request is set on null [here](https://github.com/biigle/user-storage/blob/e41f565f7a7d8216af1806a42ca7407ad41ebfc5/src/resources/assets/js/createContainer.vue#L463).

2024-05-27 11:56 UTC, lehecht commented on src/resources/assets/js/createContainer.vue
> -                chunkIndex += 1;
I moved it because if [this](https://github.com/biigle/user-storage/blob/e41f565f7a7d8216af1806a42ca7407ad41ebfc5/src/resources/assets/js/createContainer.vue#L442) promise failed, I got errors on the console. The promise was never catched in the catch branch because it was splitted.

2024-05-28 05:58 UTC, lehecht commented on src/resources/assets/js/createContainer.vue
> +                .then(function (res) {
The response is used [here](https://github.com/biigle/user-storage/blob/e41f565f7a7d8216af1806a42ca7407ad41ebfc5/src/resources/assets/js/createContainer.vue#L490).

2024-05-28 07:16 UTC, mzur commented on src/Http/Controllers/Api/StorageRequestFileController.php
> +                $fileModel = $fileModel->refresh();
Then you probably have to add `retry_count => 1` to the call to `create()` above. The case where the file already exists should have the correct `retry_count`. Then you could save one DB query by removing `refresh()`.

2024-05-28 07:30 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> +                }
So this case could happen when the first of multiple (chunked) files fails? Like this:

1. Upload chunked file 1, which fails.
2. Delete the whole storage request because it was the only file.
3. Continue to file 2.
4. The storage request was deleted so a new one is created.

If this is correct then maybe you can just remove the code to create a new storage request in `handleSubmit()`. We don't need two locations where the storage request is created.

2024-05-28 08:02 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> -                chunkIndex += 1;
The error should bubble up until it is handled in `uploadFile()`. But you are right that there could be a case where an error is not caught. This is the `throw e` case here. This should be solved if you do:

```js
let promise = this.uploadBlob(...);
start = end;
chunkIndex += 1;
promise = promise.then(...).catch(...);
```
The last line includes the change where the promise is updated to also include the case of `throw e` which will now bubble up. With this you can also remove the `start = end` from the `then()` again.

I'm focusing on this because right now I don't recall why `start` and `chunkIndex` were directly modified after calling `uploadBlob()`. With your change this may happen "too late". So I try to keep this as much as possible as it was before.

2024-05-28 08:04 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> +                .then(function (res) {
I see! This was probably the reason why I split the promise in the first place.

2024-05-29 07:09 UTC, lehecht commented on src/resources/views/create.blade.php
> +            <span>files with a total size of <span v-text="totalSizeForHumans()"></span>.</span>
Should I then add another loading component for failed files or combine e.g. `totalSize` and `totalSizeFailedFiles` in another computed prop that is used for the loading component?

2024-06-03 11:53 UTC, lehecht commented
How should a storage requests be handled if all files were uploaded successfully but the request couldn't be updated at the end?

2024-06-03 13:06 UTC, mzur commented
No, just keep it like that. The user should be able to click submit again (right?). Also, they could reload the page and find the storage request still pending. Then they can click submit again, too.

2024-06-06 09:06 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> +                let retryChunkTrue = 1;
You still don't set `retryChunk` in the [error callback](https://github.com/biigle/user-storage/blob/454141cc049728b872c96684c89a83c57047e605/src/resources/assets/js/createContainer.vue#L434).

2024-06-06 09:18 UTC, mzur requested changes
Some previous comments are not resolved yet. Also, I don't see the failed/duplicate file states in the UI any more (i.e. changed color and icon):

![image](https://github.com/biigle/user-storage/assets/2457311/4ee29906-299b-47f5-8366-325bd3f3686b)

2024-06-07 07:18 UTC, lehecht commented
> Some previous comments are not resolved yet. Also, I don't see the failed/duplicate file states in the UI any more (i.e. changed color and icon):

I don't know how to reproduce this bug. For me everything seems to work. Can you describe what you did?

2024-06-07 08:03 UTC, lehecht commented on src/Http/Controllers/Api/StorageRequestFileController.php
> +                    return $fileModel;
Should the retry option be set on true for ordinary files?

2024-06-10 09:53 UTC, lehecht commented on src/resources/assets/js/createContainer.vue
> +                    this.finished = !this.finishIncomplete && !hasError;
It cannot be deleted here, but you are right that it is not necessary to set it twice. I remove the line in `maybeFinishSubmission`.

2024-06-12 08:31 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> +                    this.finished = !this.finishIncomplete && !hasError;
Why can't it be deleted here? If it is set in `maybeFinishSubmission` then it is set only if there is no error, just like you do in `finally`. Then there is no need for the extra `hasError`. Maybe you need to set `this.finished = false` before the upload starts?

2024-06-12 08:42 UTC, mzur reviewed
Almost finished! Only one comment now. And maybe it's a good idea to add a second test case for a chunked file upload that is retried now. Finally, could you clarify the discussion about `this.finished` above?

2024-06-12 08:42 UTC, mzur commented on src/resources/views/create.blade.php
> +            You have selected more than the <span v-text="availableQuota"></span> of storage available to you.
You can still show `remainingQuota`, as it is more helpful.
```suggestion
            You have selected more than the <span v-text="remainingQuota"></span> of storage available to you.
```

2024-06-13 10:46 UTC, lehecht commented on src/resources/assets/js/createContainer.vue
> +                    this.finished = !this.finishIncomplete && !hasError;
Moreover, `hasError` is used to show the submit button again if `maybeFinishSubmission` throws an error, so the user can retry the submission.

2024-06-14 07:39 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> +                    this.finished = !this.finishIncomplete && !hasError;
> It cannot be set in `maybeFinishSubmission`, because then `this.finished` will be never set on true. 

Right, it was not set to true there because `this.failedFiles` was not set at this point. But it could just have been `this.finished = true` there as well, as far as i can see.

> `this.finished` depends on `this.finishIncomplete` which depends on the failed files. Those can only be updated in the `finally()` branch, because otherwise `this.failedFiles` would be read and written simultaneously. 

I see. I think it's a little convoluted there at this point. So `this.finished` should be true if there are no failed files and there was no error. What about this:

```js
this.startLoading();
let files = reupload ? this.failedFiles : this.files;
this.finished = false;

this.uploadAllFiles(files)
    .then(() => this.failedFiles = this.getFailedFiles())
    .then(this.maybeFinishSubmission)
    .catch(this.handleErrorResponse)
    .finally(() => {
        this.finishLoading();
        this.resetSizes();
    });
```
and
```js
maybeFinishSubmission() {
    if (!this.ignoreFiles && this.failedFiles.length > 0 || this.noFilesUploaded) {
        return Promise.resolve();
    }

    return StorageRequestApi.update({ id: this.storageRequest.id }, {})
        .then(() => {
            this.ignoreFiles = false;
            this.finished = true;
        });
},
```

This will 1) set `this.finished` at the location where the submission is actually finished, 2) reuse `this.failedFiles` in `maybeFinishSubmission()` and 3) remove `hasError` (also see below). Do you see any issues with that approach?

> Moreover, `hasError` is used to show the submit button again...

Do you mean the `hasError` computed property, which is something different than `hasError` here? In fact, I don't see any use of the `hasError` computed property for a button. It's used to hide the success message in case of an error. But maybe this is not even needed any more with the approach described above? Then the whole computed property can be removed as well.

2024-06-14 08:54 UTC, lehecht commented on src/resources/assets/js/createContainer.vue
> +                    this.finished = !this.finishIncomplete && !hasError;
Unfortunately, this doesn't work.
If an error occurs, `this.failedFiles` are not updated any more. Now only the message is shown, but not the option to retry.

2024-06-14 08:57 UTC, mzur commented on src/resources/assets/js/createContainer.vue
> +                    this.finished = !this.finishIncomplete && !hasError;
Correct, thanks! Then we leave it like it is :+1:

2024-06-14 08:57 UTC, merged